[Xorg_recordproto]
git-tree-sha1 = "be26e546708f67fdc8a9187fa0a198f301959dea"

    [[Xorg_recordproto.download]]
    sha256 = "44771ca4cc4576c535475f3f3027de3783834163529e1b8025a4ca25a6b73afc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_recordproto_jll.jl/releases/download/Xorg_recordproto-v1.14.2+1/Xorg_recordproto.v1.14.2.any.tar.gz"
