# Autogenerated wrapper script for Xorg_recordproto_jll for any
JLLWrappers.@generate_wrapper_header("Xorg_recordproto")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
